# LIBRETA DE TRABAJO

## 1. Crear entorno virtual
'python3 -m venv .venv
source .venv/bin/activate'

## 2. Importar librerias Python
'pip install -r requirements.txt'

## 3. Generar un Data frame desde la base de datos.csv

In [3]:
import pandas as pd
df = pd.read_csv ("penguins_raw.csv")
df

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,PAL0910,64,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N98A2,Yes,2009-11-19,55.8,19.8,207.0,4000.0,MALE,9.70465,-24.53494,NaN
340,PAL0910,65,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N99A1,No,2009-11-21,43.5,18.1,202.0,3400.0,FEMALE,9.37608,-24.40753,Nest never observed with full clutch.
341,PAL0910,66,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N99A2,No,2009-11-21,49.6,18.2,193.0,3775.0,MALE,9.46180,-24.70615,Nest never observed with full clutch.
342,PAL0910,67,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N100A1,Yes,2009-11-21,50.8,19.0,210.0,4100.0,MALE,9.98044,-24.68741,NaN
343,PAL0910,68,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N100A2,Yes,2009-11-21,50.2,18.7,198.0,3775.0,FEMALE,9.39305,-24.25255,NaN

## 4 Consultas básicas, número de individuos, especies y distribucion en las silas

In [4]:

# Contar cuantas especies se han detectado
conteo_de_espeies = df.groupby('Species').size().reset_index(name='Count')
print("Las especies detectadas son: ")
print(conteo_de_espeies, "\n")
df


# Contar cuantas especies se han detectado por isla
avistamientos_por_isla = df.groupby(['Species', 'Island']).size().reset_index(name='Count')
print("Los avistamientos de especiespor isla son: ")
print(avistamientos_por_isla, "\n")

df['Island'].value_counts()

# Contar en cuántas islas aparece cada individuo
islands_por_individuo = df.groupby('Individual ID')['Island'].nunique()

# Filtrar los que aparecen en más de una isla
duplicados = islands_por_individuo[islands_por_individuo > 1]

if not duplicados.empty:
    print("Individual IDs presentes en múltiples islas:")
else:
    print("No hay Individual IDs en más de una isla.")

detalle = df.groupby('Individual ID')['Island'].unique()

duplicados_detalle = detalle[detalle.apply(len) > 1]

print(duplicados_detalle)

Las especies detectadas son:
                                     Species  Count
0        Adelie Penguin (Pygoscelis adeliae)    152
1  Chinstrap penguin (Pygoscelis antarctica)     68
2          Gentoo penguin (Pygoscelis papua)    124

Los avistamientos de especiespor isla son:
                                     Species     Island  Count
0        Adelie Penguin (Pygoscelis adeliae)     Biscoe     44
1        Adelie Penguin (Pygoscelis adeliae)      Dream     56
2        Adelie Penguin (Pygoscelis adeliae)  Torgersen     52
3  Chinstrap penguin (Pygoscelis antarctica)      Dream     68
4          Gentoo penguin (Pygoscelis papua)     Biscoe    124

Individual IDs presentes en múltiples islas:
Individual ID
N1A1     [Torgersen, Biscoe]
N1A2     [Torgersen, Biscoe]
N21A1        [Dream, Biscoe]
N21A2        [Dream, Biscoe]
N22A1        [Dream, Biscoe]
                ...
N73A2     [Torgersen, Dream]
N7A1     [Torgersen, Biscoe]
N7A2     [Torgersen, Biscoe]
N8A1     [Torgersen, Biscoe]
N8A2     [Torgersen, Biscoe]
Name: Island, Length: 78, dtype: object

## 5 Correción de formato de fecha

In [12]:
df['Date Egg'] = pd.to_datetime(df['Date Egg'], dayfirst=True, errors='coerce')
df['Date Egg'] = df['Date Egg'].dt.strftime('%d/%m/%Y')
df

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,11/11/2007,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,11/11/2007,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,16/11/2007,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,16/11/2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,16/11/2007,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,PAL0910,64,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N98A2,Yes,19/11/2009,55.8,19.8,207.0,4000.0,MALE,9.70465,-24.53494,NaN
340,PAL0910,65,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N99A1,No,21/11/2009,43.5,18.1,202.0,3400.0,FEMALE,9.37608,-24.40753,Nest never observed with full clutch.
341,PAL0910,66,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N99A2,No,21/11/2009,49.6,18.2,193.0,3775.0,MALE,9.46180,-24.70615,Nest never observed with full clutch.
342,PAL0910,67,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N100A1,Yes,21/11/2009,50.8,19.0,210.0,4100.0,MALE,9.98044,-24.68741,NaN
343,PAL0910,68,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N100A2,Yes,21/11/2009,50.2,18.7,198.0,3775.0,FEMALE,9.39305,-24.25255,NaN